Augment hotels with regular price
FindHotel/sapi pull request #34
Opened 2021-06-09 10:54 UTC by votsa

## Description

## Clubhouse Story

https://app.clubhouse.io/findhotel/story/34453/spike-expose-deal-score-in-sapi

[ch34453]

## Additional info

2021-06-09 12:57 UTC, jopdeklein commented on packages/core/src/search.ts
> +function augmentHotelWithRegularPrice(
Should we call this `regularHistoricalPriceRange`? Just regular could be mixed up with something like prices with taxes etc. And range because it's a range :D

2021-06-09 12:57 UTC, jopdeklein commented on packages/core/src/search.ts
> +      loadOffers: async (hotelId) => {
Nice :)

2021-06-14 10:21 UTC, votsa commented on packages/core/src/utils/omit.ts
> +import {Except} from 'type-fest'
Just moved it to separate file

2021-06-14 10:21 UTC, votsa commented on packages/core/src/utils/omit.test.ts
> +import {omit} from './omit'
Just moved it to separate file

2021-06-14 10:21 UTC, votsa commented on packages/core/src/utils/search-id.test.ts
> +import {generateSearchId} from './search-id'
Just moved it to separate file

2021-06-14 10:21 UTC, votsa commented on packages/core/src/utils/search-id.ts
> +import hash from 'object-hash'
Just moved it to separate file

2021-06-14 10:21 UTC, votsa commented on packages/core/src/utils/state.ts
> +import {produce, Draft} from 'immer'
Just moved it to separate file

2021-06-14 10:49 UTC, velppa commented on packages/core/src/utils/deal-score.ts
> +export type DealScores = Record<HotelId, number>
I [learned](https://stackoverflow.com/questions/51936369/what-is-the-record-type-in-typescript) about Map type in TypeScript and in this case - unbounded values of key, HotelId; while Record implies some closed group of keys. Based on that it looks like Map should be used instead of Record in this case.


```typescript
Map<HotelId, number>
```

Or I understood it wrong?

2021-06-14 10:56 UTC, jopdeklein requested changes

2021-06-14 10:56 UTC, jopdeklein commented on packages/core/CHANGELOG.md
> +## v0.0.15
⚛️

2021-06-14 10:56 UTC, jopdeklein commented on packages/core/src/utils/deal-score.test.ts
> +  it('returns empty deal scores object if no hotels', () => {
```suggestion
  it('returns empty deal scores object if there are no hotels', () => {
```

2021-06-14 10:56 UTC, jopdeklein commented on packages/core/src/utils/deal-score.test.ts
> +  it('returns correct deal scores object when no available hotels', () => {
```suggestion
  it('returns correct deal scores object if there are no available hotels', () => {
```

2021-06-14 10:56 UTC, jopdeklein commented on packages/core/src/utils/deal-score.test.ts
> +  it('returns correct deal scores object when there is only 1 hotel in results', () => {
```suggestion
  it('returns correct deal score object when there is only 1 hotel in results', () => {
```

2021-06-14 10:56 UTC, jopdeklein commented on packages/core/src/utils/deal-score.test.ts
> +  it('returns correct deal scores object when some hotels dont have historical price', () => {
I think we should be consistent in our naming, should it be regular or historical price? (I like the latter more). I know this impacts the rest of the PR but it's easier to grasp IMO.

2021-06-14 10:56 UTC, jopdeklein commented on packages/core/src/utils/deal-score.ts
> +    const [hotelId, cheapestRate, regularFrom, regularTo] = item
```suggestion
    const [hotelId, cheapestRate, historicalLowerBound, historicalUpperBound] = item
```

I prefer lower / upper bound because the from / to implicates a "discount" in some way, like the "from" price.

2021-06-14 10:56 UTC, jopdeklein commented on packages/core/src/utils/deal-score.ts
> +    const [hotelId, cheapestRate, regularFrom, regularTo] = item
The typing helps, but I prefer to just spell these out in the function signature directly rather than the `DealScoreInput`. It's not quite clear which parts are optional or not and which can be omitted.

2021-06-14 10:56 UTC, jopdeklein commented on packages/core/src/utils/discount.ts
> +export function calculateDiscount(rate: number, from?: number, to?: number) {
Here I also prefer the lower  / upper bound naming over the from / to to avoid confusion (especially since this is dealing with a discount :))

2021-06-14 10:56 UTC, jopdeklein commented on packages/core/src/utils/discount.ts
> +  return rate < from
For me the nested ternary operators are hard to parse, especially since the branches look so similar. Maybe in this case an if/if else/else is easier to grasp?

2021-06-14 10:58 UTC, jopdeklein commented on packages/core/src/utils/deal-score.ts
> + * @param parameters - parameters used to calculate deal score
I believe we should expand this documentation with what a deal score is, or at least that it is a number between 0 and 1 (or whichever scale we do or will support).

2021-06-14 11:05 UTC, velppa commented on packages/core/src/utils/deal-score.ts
> +export type DealScores = Record<HotelId, number>
Update - turns out Map is hard to use in practice, it won't created out of object automatically, so I switched to Record back.
https://github.com/FindHotel/website-content/pull/12/commits/6ce045fe181905c0f7561b549a81e95302167274

2021-06-14 12:02 UTC, votsa commented on packages/core/src/utils/deal-score.test.ts
> +  it('returns correct deal scores object when some hotels dont have historical price', () => {
It's regular historical price. (we have regular for weekdays and prices for the weekends)

2021-06-14 12:22 UTC, votsa commented on packages/core/src/utils/deal-score.ts
> +    const [hotelId, cheapestRate, regularFrom, regularTo] = item
But how we should do that? The function requires an array of values as we calculate deal score related to the list of the hotels, not for an individual hotel.

2021-06-14 12:22 UTC, jopdeklein commented on packages/core/src/utils/deal-score.test.ts
> +  it('returns correct deal scores object when some hotels dont have historical price', () => {
OK clear, should we then call it `regularHistorical` or `weekdayHistorical` ?

2021-06-14 12:29 UTC, votsa commented on packages/core/src/utils/deal-score.test.ts
> +  it('returns correct deal scores object when some hotels dont have historical price', () => {
Not a `weekday` or `weekend` as we use `medianRateBkt` which covers both. I agree that the name then looks more verbose but it's quite long as well `regularHistoricalLowerBound` and `regularHistoricalUpperBound`.  which make the function bigger and adds more lines to the code. Wouldn't it be better to use shorter names but with description in the comment for the function?

2021-06-14 12:31 UTC, jopdeklein commented on packages/core/src/utils/deal-score.ts
> +    const [hotelId, cheapestRate, regularFrom, regularTo] = item
I meant by defining the names in the type, it's a bit verbose but the intent is more clear:
```
[
  hotelId: HotelId,
  cheapestRate?: number,
  regularHistoricalBounds: [lowerBound: number, upperBound: number],
] 
```

Or by passing objects if you think's less verbose?

2021-06-14 12:45 UTC, votsa commented on packages/core/src/utils/deal-score.ts
> +    const [hotelId, cheapestRate, regularFrom, regularTo] = item
No, I don't like passing an object here. It will make the test function huge... Check [this test ](https://github.com/FindHotel/sapi/pull/34/files#diff-ad1cf1caf9f049f509be77dbb816d8d3559edc9c3064f180df2237c667b69b0fR201) and imagine that we should add key to each value... 
The named tuple type looks ok to me.

2021-06-14 12:47 UTC, votsa commented on packages/core/src/utils/deal-score.ts
> + * @param parameters - parameters used to calculate deal score
Probably @velppa can help with the description?

2021-06-14 13:05 UTC, jopdeklein approved these changes

2021-06-14 13:12 UTC, merged